# fly.toml app configuration file generated for simple-todos on 2024-08-05T16:29:57+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simple-todos'
primary_region = 'arn'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_URL = "https://simple-todos.fly.dev/"
  APP_ENV = 'production'
  DB_CONNECTION= 'sqlite'
  DB_DATABASE= '/var/www/html/storage/database/database.sqlite'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[mounts]
  source="storage_vol"
  destination="/var/www/html/storage"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[[vm]]
  size = 'shared-cpu-1x'
